name: Delete Message Cron Job

on:
  schedule:
    - cron: '0 18 */15 * *'

jobs:
  cron:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ./delete-message-cron-job/requirements.txt

      - name: Run Script
        run: python3 ./delete-message-cron-job/main.py
        env:
          BOT_TOKEN: ${{ secrets.DELETE_BOT_TOKEN }}
          GUILD_ID: ${{ secrets.DELETE_GUILD_ID }}
          CHAT_CHANNEL_ID: ${{ secrets.DELETE_CHAT_CHANNEL_ID }}
          LOG_CHANNEL_ID: ${{ secrets.DELETE_LOG_CHANNEL_ID }}
