name: Lostark Adventure Island Cron Job

on:
  schedule:
    - cron: '0 21 * * *'
    - cron: '0 6 * * *'

jobs:
  cron:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Setup Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Seoul"

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r ./lostark-adventure-island-cronjob/requirements.txt

      - name: Run Script
        run: |
          chmod +x ./lostark-adventure-island-cronjob/doing.sh
          sh -c ./lostark-adventure-island-cronjob/doing.sh
        env:
          WEBHOOK_LIST: ${{ secrets.LOSTARK_WEBHOOK_LIST }}
          WEBHOOK_USERNAME: ${{ secrets.LOSTARK_WEBHOOK_USERNAME }}
          WEBHOOK_AVATAR_URL: ${{ secrets.LOSTARK_WEBHOOK_AVATAR_URL }}
          DATA_SOURCE: ${{ secrets.LOSTARK_DATA_SOURCE }}
